### ISSUE TITLE
TypeError: Cannot call method 'prepEnv' of undefined

### ISSUE THREAD

**Issue by masakura** [GrayBullet/grunt-cordova-ng#1]
Error running `cordova:build` task with `--cordova-device=device' option.

```
$ grunt cordova:build --cordova-device=device
Running "cordova:build" (cordova) task

/home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot call method 'prepEnv' of undefined
    at Object.module.exports.run (/home/masakura/tmp/hoge5/platforms/android/cordova/lib/build.js:326:20)
    at /home/masakura/tmp/hoge5/platforms/android/cordova/build:36:22
    at _fulfilled (/home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:760:13)
    at /home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:574:44
    at flush (/home/masakura/tmp/hoge5/platforms/android/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
Warning: /home/masakura/tmp/hoge5/platforms/android/cordova/build: Command failed with exit code 8 Use --force to continue.

Aborted due to warnings.
```

**Comment by rvanbaalen** [comment]
@chrisb You are a freakin hero!

I do not use grunt-cordova-ng at all but had the same problem. It was caused by my cordova command:

```sh
$ cordova build --release --device
```

Thinking about it afterwards, it doesn't make sense to use both flags. When I removed the `--device` flag, no more problems existed.

**Comment by masakura** [comment]
`--device flag` is necessary in order to work with iOS Device. Can not be omitted.

You resolved by building the android and ios separately.

```
$ grunt cordova:build --cordova-platforms=ios --cordova-build=release --cordova-device=device
$ grunt cordova:build --cordova-platforms=android --cordova-build=release
```

or

```
$ cordova build ios --release --device
$ cordova build android --release
```

I want to fix this bug. It has been delayed. Sorry.

**Comment by rvanbaalen** [comment]
Like I said I dont use this project I just got here by googling the issue. I was always building both platforms seperatley but didnt know about omitting the --device flag for android which was causing this error apparently. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by masakura** [comment]
I understand. It was good, your problem has been resolved.
